### ISSUE TITLE
Issue involving Patching files

### ISSUE THREAD

**Issue by Digital-Story** [Ich73/GamePatcher#1]
ive tried doing them myself but the CIAs i got from (That Site ) arnt workin with the patches . or im doin it wrong.

I put the cias in with the patch and all the files the Patch maker said in a specific folder, run it, and it comes out with "could not open input file" or if i rename the original cia , it comes out with "the file type is mismatch"

I dont want to have to go through Joker 2 in Japanese just so i can transfer a incarnus. or have to go through so much in DQM 2 to get monsters i can just transfer over from TW

( i asked for a Cia of both in the megathread on a certain reddit, but i dont mind doing this myself if people can help me with what im doing wrong. Ive never decrypted a CIA file either so are the (That Site) cias not decrypted?)

**Comment by Ich73** [comment]
The error `"the file type is mismatch"` means that your cia file is _encrypted_. You need to _decrypt_ it with GodMode9.
- Boot the 3DS while holding START to launch Godmode9
- Navigate to the folder where your enrypted cia file is
- Navigate to the encrypted cia file and press A
- Select "CIA image options..."
- Select "Decrypt file (...)"
- Select "Decrypt inplace"
- Press A to continue
- Press START to reboot
- The cia file on your SD card is now decrypted

**Comment by Digital-Story** [comment]
> The error `"the file type is mismatch"` means that your cia file is _encrypted_. You need to _decrypt_ it with GodMode9.
> 
>     * Boot the 3DS while holding START to launch Godmode9
> 
>     * Navigate to the folder where your enrypted cia file is
> 
>     * Navigate to the encrypted cia file and press A
> 
>     * Select "CIA image options..."
> 
>     * Select "Decrypt file (...)"
> 
>     * Select "Decrypt inplace"
> 
>     * Press A to continue
> 
>     * Press START to reboot
> 
>     * The cia file on your SD card is now decrypted

THANK you that fixed it! got it working!

**Comment by EnforcerRidley** [comment]
How do I deal with `invalid literal for int() with base 10: '000a'
ERROR: Extracting Failed`?
I decrypted the cia via the method above and I verified the cia was decrypted.

**Comment by Ich73** [comment]
In the directory where `GamePatcher.exe` is located, there should be another folder with the same name as your `.cia` file. Can you send me a screenshot of the files in this directory or a list of all the file names in this directory?

**Comment by EnforcerRidley** [comment]
![image](https://github.com/Ich73/GamePatcher/assets/19423343/b2d15478-0415-4e9c-8622-98a8b97609b7)

**Comment by EnforcerRidley** [comment]
If I run it again, I get this:
![image](https://github.com/Ich73/GamePatcher/assets/19423343/09164e59-a2e4-4873-b60a-ceba57f126ec)

**Comment by Ich73** [comment]
Thanks for sending the images. The issue is because your cia file contains more "decrypted partition" files than usual, which is at most 7, but Game Patcher only uses the first 3. I don't know why your cia file contains more partitions, maybe it's a corrupted file. Perhaps patching would work if I allow for an unlimited number of partitions in the cia file and discard all but the first 3.

But first of all, I wonder if the patch file you downloaded (the `.zip` file) is suitable for my program at all. I'm assuming it's for some Fire Emblem game, and I'm not aware of any other translators using my program. I developed it for my own translations, and as far as I know, it only works for those. Maybe you're trying to patch the game with the wrong tool?

_[Edit]_ Clarification: The cia file you want to patch is a cia file for a DLC. Game Patcher is only designed for base game cias (e.g. v1.0 of a game) and update cias (e.g. v1.1 update) and not for DLCs.

**Comment by EnforcerRidley** [comment]
No Problem and thank you for getting back to me.
It's for Fire Emblem Echoes: Shadows of Valentia. This is the [mod](https://gamebanana.com/mods/487299). The mod specific to the DLC, I extracted the files from the download, then I zipped it using 7zip. Here is that zip:  
[fe15_retranslation_jpn_names-dlc-USA.zip](https://github.com/Ich73/GamePatcher/files/13852354/fe15_retranslation_jpn_names-dlc-USA.zip)

Your program seems to be required for patching the DLC, and I used this method to decrypt the cia file of the DLC:
* Boot the 3DS while holding START to launch Godmode9
* Navigate to the folder where your enrypted cia file is
* Navigate to the encrypted cia file and press A
* Select "CIA image options..."
* Select "Decrypt file (...)"
* Select "Decrypt inplace"
* Press A to continue
* Press START to reboot
* The cia file on your SD card is now decrypted

**Comment by Ich73** [comment]
Thanks for the detailed response. It looks like a classic "LayeredFS" patch to me. You don't need to "patch" the cia file, i.e. you don't need to create another cia file containing the patched content.

1) If you are playing on a real 3DS, you need to put the files (i.e. the "000A.0000004A" folders, etc.) in the `/luma/titles/` folder on your SD card.
2) If you are playing on Citra, you need to put the files (i.e. the "000A.0000004A" folders etc.) in your Citra mods folder (e.g. `C:\Users\<YourName>\AppData\Roaming\Citra\load\mods`).

Then, simply start the game and the patched content should appear.

**Comment by EnforcerRidley** [comment]
Thank you.
